apiVersion: v1
kind: Service
metadata:
  name: candidate-blueprism
  namespace: statex-apps
  labels:
    app: candidate-blueprism
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: candidate-blueprism
  ports:
    - protocol: TCP
      port: 4850
      targetPort: 80
      name: app
